### ISSUE TITLE
cannot get the sample code  to work

### ISSUE THREAD

**Issue by john-qin** [racker/falcon#408]
i try to learn falcon framework.  got stuck and cannot get the following codes to work.  if I remove __init__ it works. I dont understand why? I copied the code from the tutorial.  

import os
import time
import uuid

import falcon

def _media_type_to_ext(media_type):
	# strip off the image/ prefix
	return media_type[6:]

def _generate_id():
	return str(uuid.uuid4())

class Resource(object):

	def __init__(self, storage_path):  # remove __init__ , it works
	 	self.storage_path = storage_path  # remove __init__ , it works

	def on_post(self, req, resp):
		image_id = _generate_id()
		ext = _media_type_to_ext(req.content_type)
		filename = image_id + '.' + ext

		resp.status = falcon.HTTP_200
		resp.location = '/images/' + image_id

here's the error message, btw, I amusing python 2.7.6

(appmonkey)vagrant@vagrant-ubuntu-trusty-64:~/web/falcon$ gunicorn app
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/appmonkey/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/home/vagrant/.virtualenvs/appmonkey/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/vagrant/.virtualenvs/appmonkey/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 185, in run
    super(Application, self).run()
  File "/home/vagrant/.virtualenvs/appmonkey/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
  File "/home/vagrant/.virtualenvs/appmonkey/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 169, in run
    self.manage_workers()
  File "/home/vagrant/.virtualenvs/appmonkey/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 477, in manage_workers
    self.spawn_workers()
  File "/home/vagrant/.virtualenvs/appmonkey/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 542, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/home/vagrant/.virtualenvs/appmonkey/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 209, in handle_chld
    self.reap_workers()
  File "/home/vagrant/.virtualenvs/appmonkey/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 459, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
(appmonkey)vagrant@vagrant-ubuntu-trusty-64:~/web/falcon$

**Comment by john-qin** [comment]
my code is fine, but missing parameter in app.py.
